butcamp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.contrib.auth.views import LoginView,LogoutView
from user.views import go_to_login  ,ProfUpdate , signup , Follow


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', go_to_login,name="home"),
    url(r'^signup/$', signup , name='signup'),
    url(r'^login/$',LoginView.as_view(template_name='login.html'),name='login' ),
    url(r'^logout/$',LogoutView.as_view() ,name='logout' ),
    url(r'^update/(?P<slug>\w+)/$',ProfUpdate.as_view() ,name='update' ),
    url(r'^follow/$',Follow.as_view() ,name='follow' ),
    url(r'^payam/', include(('payam.urls', 'payam'), namespace='payam')),
    url(r'^pv/', include(('privatepayam.urls', 'privatepayam'), namespace='pv')),

]

payam/urls.py
from django.conf.urls import url , include
from django.contrib.auth.views import LoginView,LogoutView

from .views import DeleteMessage , message_list , FollowingsView ,FollowersView



urlpatterns = [
    url(r'^$',message_list ,name='list' ),
    url(r'^followers/(?P<slug>\w+)/$',FollowersView.as_view() ,name='followers' ),
    url(r'^followings/(?P<slug>\w+)/$',FollowingsView.as_view() ,name='followings' ),
    url(r'^remove/(?P<pk>\d+)/$',DeleteMessage.as_view() ,name='remove' ),

]

payam/models.py
from django.db import models
from django.conf import settings

user = settings.AUTH_USER_MODEL

# Create your models here.
class Payam(models.Model):
    owner       =models.ForeignKey(user , on_delete=models.CASCADE)
    message     =models.CharField(max_length=250 ,blank=True,null=True)
    time        =models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.owner.username

payam/views.py
from django.shortcuts import render
from django.views.generic import ListView , DeleteView
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.db.models import Q


from .models import Payam
from user.models import Users
from .form import PayamForm
from privatepayam.models import Private
# Create your views here.
karbar = get_user_model()

class DeleteMessage(DeleteView):
    template_name = "delete_message.html"
    model = Payam
    success_url = "/payam"

class FollowingsView(ListView):
    template_name="followings.html"
    def get_queryset(self):
        slug =self.kwargs.get("slug")
        # user=self.request.user
        user=karbar.objects.get(username=slug)
        queryset = user.is_follow.all()
        return queryset

class FollowersView(ListView):
    template_name="followers.html"
    def get_queryset(self):
        slug =self.kwargs.get("slug")
        user=Users.objects.get(user__username=slug)
        queryset = user.follower.all()
        return queryset

def message_list(request):
    template_name="message_list.html"
    form = PayamForm()
    query=request.GET.get("q")

    prof =[x.user.id for x in request.user.is_follow.all()]
    prof.append(request.user.id)
    qs = Payam.objects.filter(owner__id__in=prof)
    context = {"form" :form , "object_list": qs}
    if query :
        context['search']=True
        context['object_list'] = karbar.objects.filter(username=query)
    if request.method == "POST":
        form = PayamForm(request.POST)
        if form.is_valid():
        	Payam.objects.create(
        		message=form.cleaned_data.get("message"),
                owner = request.user
        	)
        return HttpResponseRedirect("/payam")
    mabda=request.user.username
    newpv = Private.objects.filter(Q( dest__username=mabda , read=False))
    context['newpv']=newpv.exists()

    return render(request , template_name , context)

payam/templates/delete_message.html
{% extends "base.html" %}

{% block head %}
    delete || {{block.super}}
{% endblock %}

{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }

</style>
<div class="card text-center border-danger mb-3" style="width: 30rem; margin:auto; ">
  <div class="card-header ">
    <h1>
        Delete : {{object}}
        &emsp;
       <small><a class="btn btn-outline-danger"style="color : red; text-decoration:none;" href="{% url 'payam:list'  %}">Back</a></small>
    </h1>
  </div>
  <div class="card-body ">
    <div class="card-text">
      <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object.message }}"?</p>
          <input class="btn btn-danger" type="submit" value="Confirm" />
      </form>
    </div>
  </div>


</div>


{% endblock %}

payam/templates/followers.html
{% extends "base.html" %}

{% block head %}
  followings | {{block.super}}
{% endblock %}


{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }

</style>

<div class="list-group mb-3" style="width:25rem;margin-left:25%;">
  <a  class="list-group-item list-group-item-action"><h3>followers List</h3></a>
  {% for item in object_list %}
    <a  href="{% url "update" slug=item %}" class="list-group-item list-group-item-action list-group-item-secondary">{{item}}</a>
  {% endfor %}
</div>
{% endblock %}

payam/templates/followings.html
{% extends "base.html" %}

{% block head %}
  followings | {{block.super}}
{% endblock %}


{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }

</style>
<div class="list-group mb-3" style="width:25rem;margin-left:25%;">
  <a  class="list-group-item list-group-item-action"><h3>followings List</h3></a>
  {% for item in object_list %}
    <a  href="{% url "update" slug=item.user %}" class="list-group-item list-group-item-action list-group-item-secondary">{{item.user.username}}</a>
  {% endfor %}
</div>

{% endblock %}

payam/templates/message_list.html
{% extends "base.html" %}

{% block head %}
  messages | {{block.super}}
{% endblock %}


{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }
</style>

<div class="card " style="width:25rem;margin-left:25%;">
  <div class="card-body text-center">

    <form class="form-inline text-center" method="get">
          <div class="form-group mx-sm-3 mb-2">
            <input type="text" name="q"  placeholder="user"autofocus onfocus="this.value=''" value='{{request.GET.q}}'>

          </div>
        <button class="btn btn-danger " type="submit" >search</button>
        </form>

    <form class="form-inline text-center" method="post">
      {% csrf_token %}
        <div class="form-group mx-sm-3 mb-2">
          {{form.as_p}}
        </div>
      <button type="submit" class="btn btn-danger btn-lg mb-2" >post</button>

    </form>

  </div>

</div>

<hr>
{% for item in object_list %}
{% if search %}
<div class="list-group mb-3 "style="width:25rem;margin-left:25%;">
    <a class="list-group-item list-group-item-dark list-group-item-action" href="{% url 'update' slug=item.username %}">
      {{item}}
    </a>
</div>


{% else %}
<div class="card text-center border-danger mb-3" style="width: 30rem; margin:auto; ">
  <div class="card-header ">
    <a class=" card-link action text-dark  " style="font-size:1.5em; " href="{% url 'update' slug=item.owner %}">{{item.owner}}</a>
    {% if item.owner == request.user %}
      &emsp;
      <span >
        <a href="{% url 'payam:remove' pk=item.id %}" >
          <button type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </a>
      </span>
    {% endif %}
  </div>
  <div class="card-body ">
    <div class="card-text">
        <p>{{item.message}}</p>
    </div>

  </div>
  <div class="card-footer ">
    <span>{{item.time|timesince}}</span>
  </div>

</div>
{% endif %}

{% endfor %}

{% endblock %}