butcamp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url , include
from django.contrib.auth.views import LoginView,LogoutView
from user.views import go_to_login  ,ProfUpdate , signup , Follow


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', go_to_login,name="home"),
    url(r'^signup/$', signup , name='signup'),
    url(r'^login/$',LoginView.as_view(template_name='login.html'),name='login' ),
    url(r'^logout/$',LogoutView.as_view() ,name='logout' ),
    url(r'^update/(?P<slug>\w+)/$',ProfUpdate.as_view() ,name='update' ),
    url(r'^follow/$',Follow.as_view() ,name='follow' ),
    url(r'^payam/', include(('payam.urls', 'payam'), namespace='payam')),
    url(r'^pv/', include(('privatepayam.urls', 'privatepayam'), namespace='pv')),

]

payam/urls.py
from django.conf.urls import url , include
from django.contrib.auth.views import LoginView,LogoutView

from .views import DeleteMessage , message_list , FollowingsView ,FollowersView



urlpatterns = [
    url(r'^$',message_list ,name='list' ),
    url(r'^followers/(?P<slug>\w+)/$',FollowersView.as_view() ,name='followers' ),
    url(r'^followings/(?P<slug>\w+)/$',FollowingsView.as_view() ,name='followings' ),
    url(r'^remove/(?P<pk>\d+)/$',DeleteMessage.as_view() ,name='remove' ),

]

privatepayam/urls.py
from django.conf.urls import url , include
from django.contrib.auth.views import LoginView,LogoutView


from .views import PVList , ListOfPV 


urlpatterns = [

    url(r'^to/(?P<slug>\w+)/$',PVList.as_view() ,name='to' ),
    url(r'^send/$',ListOfPV.as_view() ,name='send' ),
    # url(r'^remove/(?P<slug>\w+)/$',RemovePVList.as_view() ,name='remove' ),
]

templates/base.html
{% load static %}
<!DOCTYPE>

<html>

<head>
    <div class="head">
        <title>

            {% block head %} butcamp {% endblock %}

        </title>
    </div>

</head>

<body id="body" >

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark  mb-3" style="padding-left:35%;">
          <a class="navbar-brand text-danger " href="/">Butcamp</a>

          <div class="collapse navbar-collapse m-3" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto  ">
              {% if user.is_authenticated %}
              <li class="nav-item ml-3">
                <a class="btn btn-outline-danger " href="{% url "update" slug=user.username %}" >{{request.user.username}}</a>
              </li>
              <li class="nav-item ml-3">
                <a class="btn btn-light " href="{% url "logout" %}" >Logout</a>
              </li>
              {% else %}
              <li class="nav-item active ml-5">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              {% endif %}
              {% if newpv %}
              <li class="nav-item active ml-5">
              <a href="{% url 'pv:send' %}"type="button" class="btn btn-primary">
                messages &ensp; <span class="badge badge-warning ">new</span>
              </a>
              </li>
              {% else %}
              <li class="nav-item active ml-5">
              <a href="{% url 'pv:send' %}" type="button" class="btn btn-primary">
                messages
              </a>
            </li>
              {% endif %}

            </ul>
          </div>

      </nav>

      <div class="content" style=" background-color:white; border:1px solid black; padding-top:20px; margin-top: 25px;margin-right: 25%; margin-left: 25%;text-align:center; " >
        {% block content %}
        {% endblock content %}
      </div>

	</div>


{% include "snippet/css.html" %}


</body>



</html>

templates/login.html
{% extends "base.html" %}

{% block head %}
  Login | {{block.super}}
{% endblock %}

{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }

</style>
{% if not user.is_authenticated %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
<form class="form"  method="post" action="{% url 'login' %}">{% csrf_token %}


<div class="form-group" style="padding-left:30%;" >
  <table>
  <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
  </tr>
  <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
  </tr>
  </table>
</div>

<input class="btn btn-danger" type="submit" value="login" />
<a class="btn btn-primary" href="{% url  'signup' %}">signup</a>
<input type="hidden" name="next" value="{{ next }}" />



</form>


<!-- <form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
{% else %}
<p>to see other people post  <a href="{% url "payam:list" %}">click here</a> </p>

{% endif %} -->


{% endblock content %}

templates/prof_update.html
{% extends "base.html" %}

{% block head %}
  test | {{block.super}}
{% endblock %}


{% block content %}
{% if request.user == object.user  %}

<style media="screen">

  #body{background-color:{{color}};}
  a{color : red; text-decoration:none;}
</style>
{% else %}
<style media="screen">
  #body{background-color:{{color}};}
  a{color : red; text-decoration:none;}
</style>
{% endif %}



<div class="card ">
  <div class="card-header">

    <h1>
      {{ object.user.username }}
     {% if not request.user == object.user  %}
        <span>{% include "snippet/follow.html" with username=object.user.username is_following=is_following %}</span>
        {% if request.user in object.follower.all %}
        <a class="btn btn-success" href="{% url 'pv:to' slug=object.user.username %}">private message</a>
        {% endif %}
      {% endif %}
    </h1>
    <small class="btn btn-outline-dark">  name:{{object.name}} </small>
    <p></p>
    <div class="btn-group" role="group" aria-label="Basic example">
    <a class="btn btn-outline-danger" href="{% url 'payam:followers' slug=object.user.username %}">followers</a>
    <a class="btn btn-outline-danger" href="{% url 'payam:followings' slug=object.user.username %}">following</a>
    <a class="btn btn-outline-danger" href="{% url 'home' %}" >Home</a>
    </div>
  </div>
  <div class="card-body">
    <p>email: {{object.email}}</p>
    <div class="list-group">
      <a  class="list-group-item list-group-item-action">Favarite</a>
      {% for item in object.get_fave %}
        <a  class="list-group-item list-group-item-action list-group-item-secondary">{{item}}</a>
      {% endfor %}
    </div>
  </div>

</div>


{% if object.user == request.user  %}
<div class="card">
  <div class="card-head">
    <h1>make changes</h1>
  </div>
  <div class="card-body">
    <form action="{% url "update" slug=object.slug %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-danger"type="submit" name="save" value="Update">
    </form>
  </div>
</div>
{% endif %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<style media="screen">
  #body{
    background-color:#ccc555;
  }

</style>
{% if not request.user.is_authenticated %}
  <h2>Sign up</h2>

  <form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-danger" type="submit">Sign up</button>
  </form>
  {% else %}
  <div class="card border-danger mb-3 " style="width:25rem;margin-left:25%;">
    <div class="card-body">
      <p class="card-text"> you're already login </p>
    </div>
  </div>
  {% endif %}
{% endblock %}